#!/usr/bin/env bash
# scripts/llm/hooks/pre-user-prompt-context.sh
# Pre-prompt context injection hook.
# Fires once per user interaction before the LLM begins reasoning.
# Injects architecture, security, and C++ style context.
# Called by platform hooks (e.g. .windsurf/hooks/pre-user-prompt.sh).

echo "=== RACKZ PROJECT CONTEXT ==="
echo ""
echo "Language: C++17. Build: CMake + GNU Make. ~174k LOC."
echo ""
echo "Architecture — src/ layer rules (each layer must not include from layers above it):"
echo "  crypto/          pure cryptographic primitives. No wallet, daemon, rpc, or protocol."
echo "  ringct/          RingCT + Bulletproofs. Depends on crypto/ and device/ (HW wallet abstraction)."
echo "  seraphis_crypto/ STUB — READ-ONLY. Do not modify."
echo "  cryptonote_basic/ tx/block structures + keys."
echo "  cryptonote_core/ consensus, blockchain, tx pool. No wallet/."
echo "  wallet/          libwallet (wallet2.cpp = 15k lines). No daemon/ internals."
echo "  net/             network abstractions. No consensus, no wallet."
echo "  p2p/             peer layer. No wallet."
echo "  rpc/             adapts core + wallet. Does not leak consensus internals."
echo ""
echo "Red zone (AI must NOT write without explicit user confirmation):"
echo "  src/crypto/  src/ringct/  src/seraphis_crypto/"
echo "  src/hardforks/  src/cryptonote_config.h"
echo ""
echo "Yellow zone (AI may write, must run tests, report results):"
echo "  src/wallet/  src/rpc/  src/p2p/"
echo ""
echo "C++ style:"
echo "  Format:       clang-format (2-space indent, 120-col limit, see .clang-format)"
echo "  Lint:         clang-tidy (see .clang-tidy)"
echo "  RAII:         prefer over manual new/delete"
echo "  Errors:       cryptonote_core/ uses CHECK_AND_ASSERT_MES + return bool;"
echo "                wallet/ uses THROW_WALLET_EXCEPTION; do not mix patterns across layers"
echo "  Threading:    use epee::critical_section or std::mutex; document thread-safety"
echo "  Includes:     no 'using namespace std;' in headers"
echo "  Macros:       minimise; prefer constexpr / enum class / templates"
echo ""
echo "Testing:"
echo "  Unit:         tests/unit_tests/ (gtest)"
echo "  Consensus:    tests/core_tests/ (chaingen)"
echo "  Functional:   tests/functional_tests/ (Python + regtest daemon)"
echo "  Fuzz:         tests/fuzz/ (27 targets)"
echo ""
echo "Before writing code, verify:"
echo "  1. Layer boundaries are respected (no forbidden #include patterns)"
echo "  2. Red-zone files: confirm with user before touching"
echo "  3. New .cpp files: does a test file exist?"
echo "  4. Public headers changed: are Doxygen comments present?"
echo "  5. No hardcoded keys, mnemonics, seeds, or API tokens"
echo "  6. Sensitive buffers cleared with memwipe() not memset()"
echo ""
echo "Style guide: docs/rackz/STYLE_GUIDE.md (naming, brace style, logging macros, typedef vs using)"
echo "=== END CONTEXT ==="
